INSERT INTO USER (USER_ID,ACTIVE,EMAIL,LAST_NAME,NAME,PASSWORD) VALUES (1,	1,	'admin@demo.com',	'Admin',	'Admin'	,'$2a$10$3Ww2KnHmhSPgmkzBP30sXekft/YojWwmei.S2rkUygxKU1IMc8IeW');

INSERT INTO ROLE (ROLE_ID, ROLE) VALUES (1, 'ADMIN');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);





